fieldLayouts:
  50f76971-f8a7-46ee-8ea5-d763f090b426:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: c85cf1b0-a152-43c8-8b75-5cbd302d32e5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ebb6eb92-b2c5-4b2b-9545-84261d64bfed
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7057efa8-9f55-4764-9f44-d8c0a6845fdf
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ee831516-2a21-4bba-9956-8b4569ab19c2
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 02f30aa1-a4ad-40cd-a8b1-806746c5698e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Home
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 78be4e7c-75f8-45bf-8930-aa9140b965b9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Brands
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 230afaff-9373-4450-b743-1486c5a658c8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5ea3d715-2251-46e9-a840-45727140485a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 04554497-09f2-4f1f-9f79-6f0bb900a031
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Testimonials
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 7c7f3a07-335e-4fe2-adeb-d11d1e6d5d96
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Brands Slider'
        sortOrder: 4
handle: home
hasTitleField: true
name: Home
section: 73f94fa1-91a8-48ce-81f4-0cad7eab21b2
sortOrder: 1
titleFormat: '{section.name|raw}'
