fieldLayouts:
  92bcc7ec-32af-47a5-8a16-51f2887e4a18:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a2e77db5-2f12-490e-b8f6-13795dc352a7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c66ccdb1-93fc-47d5-954f-90b1eeb12798
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 51b72f8a-65a4-41d5-8cc8-7f4d1c007200
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 467c32a3-0d8c-4b94-b5f5-112e7cee72ba
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9a6e5eb2-5ba7-4919-8ba4-94dfc252b458
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Testimonials
        sortOrder: 1
handle: testimonials
hasTitleField: true
name: Testimonials
section: c3ee8913-df7b-4b08-8f45-060f01cdb3cf
sortOrder: 1
titleFormat: ''
