fieldLayouts:
  fa50b207-f377-496d-89e6-82172f7aae33:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Thanks
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 65986595-a916-4e90-bcc9-4648731a7e84
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 02f30aa1-a4ad-40cd-a8b1-806746c5698e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ad3051df-2aef-4559-bebd-2502159938e4
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Thanks
        sortOrder: 1
handle: thanks
hasTitleField: true
name: Thanks
section: 7365523c-a747-4bdd-9eb1-20c02dbb6047
sortOrder: 1
titleFormat: '{section.name|raw}'
