fieldLayouts:
  53b1977d-d6ba-43db-a6d0-da061ae27ccf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blog
hasUrls: true
name: Blog
settings:
  path: '@root/web/images/blog'
sortOrder: 1
type: craft\volumes\Local
url: '@web/images/blog'
