fieldLayouts:
  3feef0c5-ab82-462a-9ebe-f25f588b3615:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: testimonials
hasUrls: true
name: Testimonials
settings:
  path: '@root/web/images/testimonials'
sortOrder: 5
type: craft\volumes\Local
url: '@web/images/testimonials'
