fieldLayouts:
  e0f588d0-c053-405c-9c40-64b7f9ca8a03:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: texture
hasUrls: true
name: Texture
settings:
  path: '@root/web/images/texture'
sortOrder: 8
type: craft\volumes\Local
url: '@web/images/texture'
