contentColumnType: string
fieldGroup: e4b48433-b7e3-491e-9931-fe5be7e39247
handle: backgroundTexture
instructions: 'Add a seamless background texture'
name: 'Background Texture'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:737ac79e-ca43-4dca-9284-464610ce75a6'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a seamless texture'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1a166201-6a7d-4b1b-a205-b4fd01b780d4'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
