contentColumnType: text
fieldGroup: 540b90d9-8f94-400c-9d2c-f103986c8d06
handle: blogSummary
instructions: 'Enter blog summary'
name: 'Blog Summary'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: 'Enter blog summary.'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
