contentColumnType: string
fieldGroup: 540b90d9-8f94-400c-9d2c-f103986c8d06
handle: blogImage
instructions: 'Add blog image'
name: 'Blog Image'
searchable: true
settings:
  contentTable: '{{%matrixcontent_blogimage}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
