contentColumnType: string
fieldGroup: 6fee036c-b72c-4ad5-8091-236fb7445c94
handle: brandSlider
instructions: 'Enter brand images'
name: 'Brand Slider'
searchable: true
settings:
  contentTable: '{{%matrixcontent_brandslider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
