contentColumnType: string
fieldGroup: 6fee036c-b72c-4ad5-8091-236fb7445c94
handle: brands
instructions: 'Enter brands'
name: Brands
searchable: true
settings:
  contentTable: '{{%matrixcontent_brands}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
