contentColumnType: text
fieldGroup: 6fee036c-b72c-4ad5-8091-236fb7445c94
handle: faqQuestions
instructions: 'Enter FAQ questions'
name: 'FAQ Questions'
searchable: true
settings:
  addRowLabel: 'Add a question.'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'FAQ Question'
            -
              - handle
              - faqQuestion
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'FAQ Answer'
            -
              - handle
              - faqAnswer
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
