contentColumnType: string
fieldGroup: e4b48433-b7e3-491e-9931-fe5be7e39247
handle: homeSlider
instructions: 'Enter information into home slider'
name: 'Home Slider'
searchable: true
settings:
  contentTable: '{{%matrixcontent_homeslider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
