contentColumnType: text
fieldGroup: dea578a7-cdda-4c2c-8531-1eeb383129df
handle: productPrice
instructions: 'Enter product price'
name: 'Product Price'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Enter product price.'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
