contentColumnType: text
fieldGroup: dea578a7-cdda-4c2c-8531-1eeb383129df
handle: productVideoTitle
instructions: 'Enter video title'
name: 'Product Video Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Enter video title.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
