contentColumnType: string
fieldGroup: 6fee036c-b72c-4ad5-8091-236fb7445c94
handle: sliderTestimonialImage
instructions: 'Add testimonial image'
name: 'Slider Testimonial Image'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:55be5bd6-0e8c-4195-8021-3b20db6f32ab'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add testimonial image.'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:55be5bd6-0e8c-4195-8021-3b20db6f32ab'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
