contentColumnType: text
fieldGroup: 6fee036c-b72c-4ad5-8091-236fb7445c94
handle: testimonialTitle
instructions: 'Enter testimonial title'
name: 'Testimonial Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Enter testimonial title.'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
