contentColumnType: text
fieldGroup: 567d39d4-2eb2-46d3-ac0c-f8a7565f04fc
handle: testimonialFormTitle
instructions: 'Enter testimonial form title'
name: 'Testimonial Form Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Enter testimonial form title.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
