contentColumnType: text
fieldGroup: 567d39d4-2eb2-46d3-ac0c-f8a7565f04fc
handle: testimonialProduct
instructions: 'Enter product purchased'
name: 'Testimonial Product'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Enter product purchased.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
