contentColumnType: string
fieldGroup: 6fee036c-b72c-4ad5-8091-236fb7445c94
handle: testimonialSlider
instructions: 'Enter testimonials'
name: 'Testimonial Slider'
searchable: true
settings:
  contentTable: '{{%matrixcontent_testimonialslider}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
