enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  35467f97-de19-45ab-b61b-0a59d1adcb4f:
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: about
type: single
