enableVersioning: true
handle: testimonials
name: Testimonials
propagationMethod: all
siteSettings:
  35467f97-de19-45ab-b61b-0a59d1adcb4f:
    enabledByDefault: true
    hasUrls: true
    template: testimonials/_entry
    uriFormat: 'testimonials/{slug}'
type: channel
