enableVersioning: true
handle: testimonialThanks
name: 'Testimonial Thanks'
propagationMethod: all
siteSettings:
  35467f97-de19-45ab-b61b-0a59d1adcb4f:
    enabledByDefault: true
    hasUrls: true
    template: thanks/_thanks
    uriFormat: testimonial/thanks
type: single
