enableVersioning: true
handle: weBuy
name: 'We Buy'
propagationMethod: all
siteSettings:
  35467f97-de19-45ab-b61b-0a59d1adcb4f:
    enabledByDefault: true
    hasUrls: true
    template: we-buy/_entry
    uriFormat: we-buy
type: single
